Add bridge-utils

diff --git a/packages/docker/packaging b/packages/docker/packaging
--- a/packages/docker/packaging
+++ b/packages/docker/packaging
@@ -5,15 +5,48 @@ set -u # report the usage of uninitialized variables
 CPUS=`grep -c ^processor /proc/cpuinfo`
 
 # We grab the latest versions that are in the directory
-DOCKER_VERSION=`ls -r docker/docker-* | sed 's/docker\/docker-\(.*\)/\1/' | head -1`
 AUFS_TOOLS_VERSION=`ls -r docker/aufs-tools_*.deb | sed 's/docker\/aufs-tools_\(.*\).deb/\1/' | head -1`
+AUTOCONF_VERSION=`ls -r docker/autoconf-*.tar.gz | sed 's/docker\/autoconf-\(.*\)\.tar\.gz/\1/' | head -1`
+BRIDGE_UTILS_VERSION=`ls -r docker/bridge-utils-*.tar.gz | sed 's/docker\/bridge-utils-\(.*\)\.tar\.gz/\1/' | head -1`
+DOCKER_VERSION=`ls -r docker/docker-* | sed 's/docker\/docker-\(.*\)/\1/' | head -1`
+
+# Extract Autoconf package
+echo "Extracting Autoconf ${AUTOCONF_VERSION}..."
+tar xzvf ${BOSH_COMPILE_TARGET}/docker/autoconf-${AUTOCONF_VERSION}.tar.gz
+if [[ $? != 0 ]] ; then
+  echo "Failed extracting Autoconf ${AUTOCONF_VERSION}"
+  exit 1
+fi
+
+# Extract bridge-utils package
+echo "Extracting bridge-utils ${BRIDGE_UTILS_VERSION}..."
+tar xzvf ${BOSH_COMPILE_TARGET}/docker/bridge-utils-${BRIDGE_UTILS_VERSION}.tar.gz
+if [[ $? != 0 ]] ; then
+  echo "Failed extracting bridge-utils ${BRIDGE_UTILS_VERSION}"
+  exit 1
+fi
+
+# Copy aufs-tools package
+echo "Copying aufs-tools ${AUFS_TOOLS_VERSION}..."
+cp -a ${BOSH_COMPILE_TARGET}/docker/aufs-tools_${AUFS_TOOLS_VERSION}.deb ${BOSH_INSTALL_TARGET}/
+
+# Build Autoconf package
+echo "Building Autoconf ${AUTOCONF_VERSION}..."
+cd ${BOSH_COMPILE_TARGET}/autoconf-${AUTOCONF_VERSION}
+./configure
+make -j${CPUS}
+make install
+
+# Build bridge-utils package
+echo "Building bridge-utils ${BRIDGE_UTILS_VERSION}..."
+cd ${BOSH_COMPILE_TARGET}/bridge-utils-${BRIDGE_UTILS_VERSION}
+autoconf
+./configure --prefix=${BOSH_INSTALL_TARGET}
+make -j${CPUS}
+make install
 
 # Copy Docker package
 echo "Copying Docker ${DOCKER_VERSION}..."
 mkdir -p ${BOSH_INSTALL_TARGET}/bin
 cp -a ${BOSH_COMPILE_TARGET}/docker/docker-${DOCKER_VERSION} ${BOSH_INSTALL_TARGET}/bin/docker
 chmod +x ${BOSH_INSTALL_TARGET}/bin/docker
-
-# Copy aufs-tools package
-echo "Copying aufs-tools ${AUFS_TOOLS_VERSION}..."
-cp -a ${BOSH_COMPILE_TARGET}/docker/aufs-tools_${AUFS_TOOLS_VERSION}.deb ${BOSH_INSTALL_TARGET}/
